package com.clinica.appmain;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DbFix implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    public DbFix(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) throws Exception {
        try {
            jdbcTemplate.execute("ALTER TABLE appointments DROP CONSTRAINT IF EXISTS CONSTRAINT_E");
            System.out.println("Constraint CONSTRAINT_E dropped successfully.");
        } catch (Exception e) {
            System.out.println("Failed to drop CONSTRAINT_E: " + e.getMessage());
        }
        try {
            // Also drop constraints related to status that might be generated by Hibernate
            jdbcTemplate.query(
                    "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.CONSTRAINTS WHERE TABLE_NAME = 'APPOINTMENTS' AND CONSTRAINT_TYPE = 'CHECK'",
                    rs -> {
                        String constraintName = rs.getString(1);
                        System.out.println("Dropping check constraint: " + constraintName);
                        jdbcTemplate.execute("ALTER TABLE appointments DROP CONSTRAINT " + constraintName);
                    });
        } catch (Exception e) {
            System.out.println("Failed to drop check constraints: " + e.getMessage());
        }
    }
}
